- name: Installing nginx
  apt: 
    name: nginx
    state: latest
- name: add application config
  template:
    src: nginx_default_config.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644
  notify: restart_nginx

