---
- name: Remove file (delete file)
  ansible.builtin.file:
    path: /var/www/html/index.nginx-debian.html
    state: absent
- name: Copy file
  ansible.builtin.copy:
    src: ~/src/newpage.html
    dest: /var/www/html/index.nginx-debian.html
    owner: root
    group: root